# Generated by Django 5.1 on 2024-08-18 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.TextField(editable=False, unique=True),
        ),
    ]
