# Generated by Django 5.1 on 2024-08-18 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_transaction_transaction_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_date',
            new_name='transaction_created_on',
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_updated_on',
            field=models.DateField(auto_now=True),
        ),
    ]
