# Generated by Django 5.1 on 2024-08-19 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_transaction_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_created_on',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_updated_on',
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_date',
            field=models.DateField(default='1999-01-02', editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='email',
            field=models.EmailField(default='default@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
