# Generated by Django 5.1 on 2024-08-18 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE OR REPLACE FUNCTION generate_random_tnx_id() RETURNS TEXT AS $$
            DECLARE
                combined_data TEXT;
                hashed_id TEXT;
                numeric_id BIGINT;

            BEGIN
                -- Concatenate row data with a UUID4
                combined_data := 
                    COALESCE(new.column1::TEXT, '') || 
                    COALESCE(new.column2::TEXT, '') || 
                    ... || 
                    uuid_generate_v4()::TEXT;

                -- Hash the combined data using SHA-256
                hashed_id := encode(digest(combined_data, 'sha256'), 'hex');
                numeric_id := ('x' || substr(encode(hashed_id, 'hex'), 1, 16))::bit(64)::bigint;

                -- Return the hashed value prefixed with 'TNX'
                RETURN 'TNX' || numeric_id::TEXT;
            END;
            $$ LANGUAGE plpgsql;
            """,
            reverse_sql="DROP FUNCTION IF EXISTS generate_random_tnx_id();"
        )
    ]
